#!/usr/bin/env mksh
# Copyright 2018 Barbarians.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Usage: await-llap
# Waits until the LLAP service is up and running and exit
# or 360s have passed and abort - whichever is sooner

ELAPSED=0
LLAP_STATUS=`$HADOOP_HOME/bin/yarn application -list | grep llap | tail -n 1 | nawk '{ print $6 }'`
while [ "$LLAP_STATUS" != "RUNNING" ]
do
  sleep 10
  ELAPSED=$(($ELAPSED + 10))
  if [ $ELAPSED -gt 360 ]
  then
    echo "timed out waiting for LLAP daemons to be assigned"
    exit -1
  fi
  LLAP_STATUS=`$HADOOP_HOME/bin/yarn application -list | grep llap | tail -n 1 | nawk '{ print $6 }'`
done

ELAPSED=0
LLAP_RUNSTATE=`$HADOOP_HOME/bin/yarn application -list | grep llap | tail -n 1 | nawk '{ print $8 }'`
while [ "$LLAP_RUNSTATE" != "100%" ]
do
  sleep 10
  ELAPSED=$(($ELAPSED + 10))
  if [ $ELAPSED -gt 60 ]
  then
     echo "timed out waiting for LLAP daemons to be initialized"
     exit -1
  fi
  LLAP_RUNSTATE=`$HADOOP_HOME/bin/yarn application -list | grep llap | tail -n 1 | nawk '{ print $8 }'`
done

# allow some time for the YARN containers to initialize
sleep 30

echo "LLAP daemons are running"
