kind: Service
apiVersion: v1
metadata:
  name: hs2-fe
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: hiveserver2
  ports:
  - name: server
    protocol: TCP
    port: 10000
    targetPort: 10000
  - name: webui-address
    protocol: TCP
    port: 10002
    targetPort: 10002
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: hs2-cs
  labels:
    app: hs2
spec:
  ports:
  - port: 10000
    name: server
  - port: 10002
    name: webui-address
  clusterIP: None
  selector:
    app: hs2
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: hs2-pdb
spec:
  selector:
    matchLabels:
      app: hs2
  minAvailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hs2
spec:
  selector:
    matchLabels:
      app: hs2
  serviceName: hs2-cs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hs2
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: 535272059665.dkr.ecr.eu-west-1.amazonaws.com/hive:latest
        securityContext:
          allowPrivilegeEscalation: false
        name: hs2
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - mountPath: /opt/barbarian/hadoop/etc/hadoop
          name: yarn-cfg-volume
        - name: hive-cfg-volume
          mountPath: /opt/barbarian/hive/conf
        - name: tez-cfg-volume
          mountPath: /opt/barbarian/tez/conf
        - name: slider-cfg-volume
          mountPath: /opt/barbarian/slider/conf
        ports:
        - containerPort: 10000
          name: server
        - containerPort: 10002
          name: webui-address
        command:
        - sh
        - -c
        - "/opt/barbarian/control/start-hiveserver2 \
          --zk_connect=zk-cs.default.svc.cluster.local \
          --rm_connect=yarn-rm-cs.default.svc.cluster.local \
          --igfs_connect=ignite-cs.default.svc.cluster.local \
          --hms_connect=hms-cs.default.svc.cluster.local:9083"
      initContainers:
      - name: start-hive-llap
        image: 535272059665.dkr.ecr.eu-west-1.amazonaws.com/hive:latest
        command:
        - sh
        - -c 
        - "HADOOP_CLASSPATH=/opt/barbarian/hadoop/etc/hadoop:/opt/barbarian/hadoop/share/hadoop/yarn/*:/opt/barbarian/hadoop/share/hadoop/yarn/lib/*:/opt/barbarian/tez/conf \
          /opt/barbarian/control/start-llap \
          --zk_connect=zk-cs.default.svc.cluster.local \
          --rm_connect=yarn-rm-cs.default.svc.cluster.local \
          --igfs_connect=ignite-cs.default.svc.cluster.local \
          --hms_connect=hms-cs.default.svc.cluster.local:9083 \
          --llapd_count=4 \
          --llapd_ram=1g"
        volumeMounts:
        - name: hive-cfg-volume
          mountPath: "/opt/barbarian/hive/conf"
        - name: tez-cfg-volume
          mountPath: "/opt/barbarian/tez/conf"
        - name: yarn-cfg-volume
          mountPath: "/opt/barbarian/hadoop/etc/hadoop"
        - name: slider-cfg-volume
          mountPath: "/opt/barbarian/slider/conf"
      - name: await-llap
        image: 535272059665.dkr.ecr.eu-west-1.amazonaws.com/hive:latest
        command:
        - sh
        - -c 
        - "/opt/barbarian/control/await-llap"
        volumeMounts:
        - name: yarn-cfg-volume
          mountPath: "/opt/barbarian/hadoop/etc/hadoop"
      volumes:
      - name: yarn-cfg-volume
        emptyDir: {}
      - name: hive-cfg-volume
        emptyDir: {}
      - name: tez-cfg-volume
        emptyDir: {}
      - name: slider-cfg-volume
        emptyDir: {}
